/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fagioligrafici2020;

import java.util.Random;

/**
 *
 * @author mr.anderson2159
 */
public class FinestraPrincipaleGiocoFagioli extends javax.swing.JFrame {
    private int n;
    private int tentativi;

    /**
     * Creates new form NewJFrame
     */
    public FinestraPrincipaleGiocoFagioli() {
        initComponents();
        Random r = new Random();
        this.n = r.nextInt(1_000_000);
        this.tentativi = 0;
    }
    
    private void bottoneActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("ho premuto");
        String s = testo.getText();
        int valoreLetto = Integer.parseInt(s);
        tentativi++;
        if (n == valoreLetto) {
            etichetta.setText("Bravo! Hai vinto in " + tentativi + "tentativi");
            bottone.setEnabled(false);
        } else if (n > valoreLetto){
            etichetta.setText("Tentativo: " + tentativi + "; il valore da indovinare è più grande");
        } else {
            etichetta.setText("Tentativo: " + tentativi + "; il valore da indovinare è più piccolo");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etichetta = new javax.swing.JLabel();
        testo = new javax.swing.JTextField();
        bottone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 1, 100, 20));

        etichetta.setText("jLabel1");
        jPanel1.add(etichetta);

        testo.setText("jTextField1");
        jPanel1.add(testo);

        bottone.setText("jButton1");
        jPanel1.add(bottone);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipaleGiocoFagioli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipaleGiocoFagioli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipaleGiocoFagioli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipaleGiocoFagioli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinestraPrincipaleGiocoFagioli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottone;
    private javax.swing.JLabel etichetta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField testo;
    // End of variables declaration//GEN-END:variables
}
